// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gerenciadortarefas.Models;

[Table("funcionariogrupo")]
public partial class Funcionariogrupo
{
    [Column("id_funcionario")]
    public int IdFuncionario { get; set; }

    [Column("id_grupo")]
    public int IdGrupo { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }

    [ForeignKey("IdFuncionario")]
    [InverseProperty("Funcionariogrupo")]
    public virtual Funcionarios IdFuncionarioNavigation { get; set; }

    [ForeignKey("IdGrupo")]
    [InverseProperty("Funcionariogrupo")]
    public virtual Grupos IdGrupoNavigation { get; set; }
}