// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gerenciadortarefas.Models;

[Table("funcionarios")]
public partial class Funcionarios
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    public string Nome { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    public string Senha { get; set; }

    [InverseProperty("IdFuncionarioNavigation")]
    public virtual ICollection<Funcionariogrupo> Funcionariogrupo { get; set; } = new List<Funcionariogrupo>();
}