// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gerenciadortarefas.Models;

[Table("grupos")]
public partial class Grupos
{
    [Key]
    [Column("id_grupo")]
    public int IdGrupo { get; set; }

    [Required]
    [Column("nome_grupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeGrupo { get; set; }

    [Column("descricao_grupo")]
    [StringLength(255)]
    [Unicode(false)]
    public string DescricaoGrupo { get; set; }

    [InverseProperty("IdGrupoNavigation")]
    public virtual ICollection<Funcionariogrupo> Funcionariogrupo { get; set; } = new List<Funcionariogrupo>();

    [InverseProperty("IdGrupoNavigation")]
    public virtual ICollection<Tarefas> Tarefas { get; set; } = new List<Tarefas>();
}