// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gerenciadortarefas.Models;

[Table("tarefas")]
public partial class Tarefas
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome_tarefa")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeTarefa { get; set; }

    [Column("descricao_tarefa", TypeName = "text")]
    public string DescricaoTarefa { get; set; }

    [Column("data_inicial", TypeName = "datetime")]
    public DateTime? DataInicial { get; set; }

    [Column("data_final", TypeName = "datetime")]
    public DateTime? DataFinal { get; set; }

    [Column("id_grupo")]
    public int IdGrupo { get; set; }

    [Column("id_status")]
    public int IdStatus { get; set; }

    [ForeignKey("IdGrupo")]
    [InverseProperty("Tarefas")]
    public virtual Grupos IdGrupoNavigation { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("Tarefas")]
    public virtual Status IdStatusNavigation { get; set; }
}